dwh_ingestion:
  outputs:
    dev:
      type: duckdb
      path: dbt.duckdb
      extensions:
        - httpfs
        - parquet
        - iceberg
      settings:
        s3_region: 'us-east-1'
        s3_endpoint: 'localhost:9000'
        s3_use_ssl: 'false'
        s3_url_style: 'path'
        s3_access_key_id: 'admin'
        s3_secret_access_key: 'password'
  target: dev
